// SMC sensor key catalogue for Intel Macs.
//
// Primary source: Fanny/SMC's Sensor.swift (MIT, © 2019 Daniel Storm) —
//   https://github.com/DanielStormApps/SMC/blob/master/smc/SMC/Sensor.swift
// Supplementary source for keys Fanny missed on T2/modern Intel Macs:
//   exelban/stats (GPL-3.0) — Modules/Sensors/list.swift treats TC%c/TC%C as
//   per-core templates and documents TCAD (CPU package), TC0E (CPU diode
//   virtual), etc.

import Foundation

enum Sensors {
    /// Candidate per-core CPU temperature keys, one slot per core index.
    /// Fanny uses uppercase `TC{i}C`; modern T2 Intel Macs sometimes expose
    /// only the lowercase `TC{i}c` variant. We try both and take whichever
    /// returns a non-zero reading. Index range 0..8 covers all Intel Mac
    /// configurations (the existence of TC0* alongside TC1*..TC8* varies by
    /// SoC generation).
    static func cpuCoreCandidates(index: Int) -> [String] {
        ["TC\(index)C", "TC\(index)c"]
    }

    /// Indices to probe for per-core CPU temperature. Covers 0..8.
    static let cpuCoreIndices: [Int] = Array(0...8)

    /// Package/die-level CPU temperature candidates in preference order:
    /// package → filtered die → diode → diode virtual → heatsink → PECI →
    /// proximity. Used when no per-core sensors are available (typical on
    /// T2 Macs which only expose a package reading).
    ///
    /// TCAD source: exelban/stats list.swift ("CPU package").
    /// Other keys source: Fanny/SMC Sensor.swift.
    static let cpuPackageKeysInPreferenceOrder: [String] = [
        "TCAD", "TC0F", "TC0D", "TC0E", "TC0H", "TCXC", "TC0P",
    ]

    /// GPU temperature sensor keys, in preference order (diode → PECI →
    /// heatsink → proximity). Source: Sensor.GPU in Fanny/SMC.
    static let gpuKeysInPreferenceOrder: [String] = [
        "TG0D", "TCGC", "TG0H", "TG0P",
    ]

    /// Number-of-fans key. Source: SMC+Fans.swift in Fanny/SMC.
    static let fanCountKey = "FNum"

    /// Per-fan keys generated by index. Source: SMC+Fans.swift in Fanny/SMC.
    static func fanCurrentRPMKey(index: Int) -> String { "F\(index)Ac" }
    static func fanMinimumRPMKey(index: Int) -> String { "F\(index)Mn" }
    static func fanMaximumRPMKey(index: Int) -> String { "F\(index)Mx" }
    static func fanTargetRPMKey(index: Int)  -> String { "F\(index)Tg" }
}
